version: "3.8"

services:
  aigerus-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://aigerus-backend:3000
    container_name: aigerus-frontend
    restart: always
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://aigerus-backend:3000
    networks:
      - aigerus-network

networks:
  aigerus-network:
    external: true
