version: "3.8"

services:
  aigerus-frontend:
    image: aigerus-frontend:latest
    container_name: aigerus-frontend
    restart: always
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
